#!/usr/bin/env python
from sys import path
from os.path import dirname, join
path.append(join(dirname(__file__), '..'))
from pylab import imshow, show

from matplotlib.pyplot import imshow
from fauxton import Action, read_scene
from fauxton import DepthSensor, SurfaceNormalSensor, VelocitySensor, read_scene

#===============================================================================
# Rendering
#===============================================================================

scene_path = join(dirname(__file__), './scene.blend')
scene = read_scene(scene_path)

scene['Camera'].resolution = (64, 64)
scene['Camera'].rotation = (0.782, 0.482, 0.213, 0.334)
pos =[(0, 3, -3, 3), (10, 3, -3, 0)]
ac = Action(position=pos)

#scene['Camera'].action = ac
vel = scene.add(VelocitySensor(pose=scene['Camera'].pose))
vel.action = ac

def render_frame(t):
    scene.time = t
    #return scene['Camera'].render()
    return vel.render()

#===============================================================================
# Visualization
#===============================================================================

for t in range(100):
    im = render_frame(t)
    im = (im**2).sum(-1)
    imshow(im)
    show()
